In [1]:
import numpy as np

**Array Operations**

Arithmetic operations

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2 #size of both array must be same

array([ 7,  9, 11, 13, 15])

In [3]:
a1-a2

array([-5, -5, -5, -5, -5])

In [4]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a1//a2

array([0, 0, 0, 0, 0])

In [7]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [8]:
l=[10,20,30,40]
arr=np.array(l)

In [9]:
arr+10 

array([20, 30, 40, 50])

In [10]:
arr1=np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [12]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow copy

In [13]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [21]:
a[4:6]*10

array([50, 60])

In [23]:
a
b=a  #deep copy
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
c=np.arange(1,21)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
d=c.copy() #shallow copy
d[0]=88
d

array([88,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [31]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [32]:
A@B #matrix multiplication

array([[19, 22],
       [43, 50]])

In [33]:
A*B

array([[ 5, 12],
       [21, 32]])

In [34]:
np.dot(A,B) #matrix multiplication

array([[19, 22],
       [43, 50]])

In [35]:
A.T #transpose

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

Stacking Array

In [36]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [37]:
np.vstack((a,b)) #vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.hstack((a,b)) #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [40]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [43]:
np.hsplit(c,4) #horizontal split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [44]:
np.vsplit(c,2) #vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
 a=np.vsplit(c,4)

In [47]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
