In [1]:
import numpy as np

**numpy indexing and slicing of vectors**

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6] #indexing

np.int64(17)

In [5]:
arr[1:5] #slicing

array([12, 13, 14, 15])

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [7]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

**numpy indexing and slicing of matrix**

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[0,0] #0th row and 0th column

np.int64(1)

In [14]:
arr[0,4]

np.int64(5)

In [15]:
arr[5][4]

np.int64(30)

In [18]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [20]:
slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**Boolean indexing**

In [43]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [45]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])