In [9]:
import numpy as np

**Valid Sudoku**

In [10]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [11]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("Sudoko is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [12]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("Sudoko is not valid")
        break
else:
    print("For columns it is valid")

For columns it is valid


In [14]:
s1=0
for i in range(0,9,3):
    for j in range(0,9,3):
        d=np.sum(s[i:i+3,j:j+3])
        print(d)
        s1+=1
if s1==9:
    print("Valid Sudoko")
else:
    print("Sudoko is not valid")

45
45
45
45
45
45
45
45
45
Valid Sudoko


In [15]:
#Columns: [Age,Maths marks,Science marks]
data=np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [23]:
#Shape of the matrix
data.shape

(5, 3)

In [25]:
#Find the average age of students
sum=0
for i in range(0,data.shape[0]):
    sum+=data[i][0]
avg=sum/data.shape[0]
print(f"Average of age is {avg}")
    


Average of age is 18.4


In [26]:
#Or
np.mean(data[:,0])

np.float64(18.4)

In [27]:
#Find maths marks of all students
for i in data:
    print(i[1])

85
92
76
65
90


In [29]:
#Find the highest science marks
np.max(data[:,2])

np.int64(95)

In [33]:
#Find details of students who scored more than 90 marks in maths
data[data[:,1]>90]

array([[19, 92, 88]])

In [32]:
#Increase maths marks of all students by 5
data[:,1]+5

array([90, 97, 81, 70, 95])

In [39]:
#Find how many students younger than 19
len(data[data[:,0]<19])

3

In [40]:
#Calculate average marks of each subject column wise
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [43]:
#Get data of sudents who scored atleast 80 marks in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [47]:
#Replace all science marks<75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])